apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-web-app
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-web-app
    spec:
      containers:
      - image: saeedhmohd244/my-go-app:latest
        name: my-go-app
        ports:
          containerPort: 8080
        resources: {}
status: {}
